#! /bin/sh
#
# Copyright (c) 2001 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# /etc/init.d/kamaeliagrey
#
# Untested
#

case "$1" in
  start)
        echo "Starting greylisting daemon"
        runGreylister.sh
        ;;
    stop)
        echo "Currently we don't support killing the greylisting daemon -"
        echo "you have to do this manually - sorry! Improvements to this"
        echo "script are welcome."
        # rc_status -v
        ;;
    status)
        echo "Currently we don't support status checking. Ought to improve this."
        echo "Improvements welcome!"
#        rc_failed 4
#        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac

