#!/bin/sh
#
# Untested
#

. /etc/rc.common

StartService ()
{
    if [ "${MAILSERVER:=-NO-}" = "-YES-" ]; then
        ConsoleMessage "Starting kamaelia logger daemon"
        /usr/local/bin/runKamaeliaLogger.sh
    fi
}

StopService ()
{
        ConsoleMessage "Currently we don't support killing the kamaelia logger daemon -"
        ConsoleMessage "you have to do this manually - sorry! Improvements to this"
        ConsoleMessage "script are welcome."
}

RestartService ()
{
    if [ "${MAILSERVER:=-NO-}" = "-YES-" ]; then
        ConsoleMessage "We don't current support reloading the kamaelia logger"
        ConsoleMessage "daemon - though killing the kamaelia logger daemon will"
        ConsoleMessage "achieve this goal. You need to do this the old"
        ConsoleMessage "fashioned way though - find the process using ps -aux"
    else
        StopService
    fi
}

RunService "$1"

