#!/usr/bin/python

import cgitb; cgitb.enable()
import os
import cgi

from kamweb import santise_env, debug_dump, serve_file, scrub_filename

base = "/srv/d_kamaelia/Sites/beta.kamaelia.org/as_published"
env = dict(os.environ)
santise_env(env)

if "debug" in env["REQUEST_URI"]:
    debug_dump(env)
else:
    path_info = scrub_filename(env["PATH_INFO"])
    filetoserve = os.path.join(base, path_info)
    if os.path.exists(filetoserve):
        if os.path.isdir(filetoserve):
            if os.path.exists(filetoserve +".html"):
                filetoserve = filetoserve +".html"
            else:
                filetoserve = os.path.join(filetoserve,"index.html")
    if not os.path.exists(filetoserve):
        filetoserve = filetoserve +".html" # Perhaps this should really redirect

    if 0:
        serve_file(filetoserve) # Useful when testing since traceback version is simpler to spot
    else:
        try:
            serve_file(filetoserve)
        except IOError:
            serve_file(os.path.join(base, "404.html"), status=404) # But this is more friendly

        